### ISSUE TITLE
How can i use the new nsfw_detector/predict.py?

### ISSUE THREAD

**Issue by mau-io** [GantMan/nsfw_model#57] opened 2020-05-06 06:10 UTC
I've been trying to use the new predict.py with these models but i couldn't.

https://github.com/GantMan/nsfw_model/releases/tag/1.1.0

do you have some example file?

**Comment by ezavesky** [comment] 2020-05-06 21:31
Recommend closing this one as a duplicate of #55

**Closed** 2020-05-06 23:59 UTC
